## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Wed Mar 13 10:09:56 Paris, Madrid 2019
##
vlib work
vcom -explicit  -93 "Carrefourfeux.vhd"
vcom -explicit  -93 "tp2_1.vhd"
vsim -t 1ps   -lib work tp2_1_vhd
view wave
add wave *
do wave.do
do {tp2_1_vhd.udo}
view structure
view signals
run 500 us
